language: java

jdk:
  - oraclejdk8

git:
  depth: 3

branches:
  only:
    - master
    - /^feature\/.+$/
    - /^v[0-9]{1,3}\.[0-9]{1,3}/

after_success:
  - ./gradlew jacocoRootTestReport coveralls

